//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Model
{

	/// <summary>
	/// 实体类zkpt_mm_desktop 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("zkpt_mm_desktop")]
	[Serializable]
	public partial class zkpt_mm_desktop : Entity 
	{
		#region Model
		private long _dId;
		private string _tmark;
		private DateTime _dAddTime;
		private string _dFilePath;
		private string _dRemark;
		/// <summary>
		/// 自增列，主键
		/// </summary>
		public long dId
		{
			get{ return _dId; }
			set
			{
				this.OnPropertyValueChange(_.dId,_dId,value);
				this._dId=value;
			}
		}
		/// <summary>
		/// 木马标识
		/// </summary>
		public string tmark
		{
			get{ return _tmark; }
			set
			{
				this.OnPropertyValueChange(_.tmark,_tmark,value);
				this._tmark=value;
			}
		}
		/// <summary>
		/// 添加时间
		/// </summary>
		public DateTime dAddTime
		{
			get{ return _dAddTime; }
			set
			{
				this.OnPropertyValueChange(_.dAddTime,_dAddTime,value);
				this._dAddTime=value;
			}
		}
		/// <summary>
		/// 图片路径
		/// </summary>
		public string dFilePath
		{
			get{ return _dFilePath; }
			set
			{
				this.OnPropertyValueChange(_.dFilePath,_dFilePath,value);
				this._dFilePath=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string dRemark
		{
			get{ return _dRemark; }
			set
			{
				this.OnPropertyValueChange(_.dRemark,_dRemark,value);
				this._dRemark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.dId;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.dId};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.dId,
				_.tmark,
				_.dAddTime,
				_.dFilePath,
				_.dRemark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._dId,
				this._tmark,
				this._dAddTime,
				this._dFilePath,
				this._dRemark};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","zkpt_mm_desktop");
			/// <summary>
			/// 自增列，主键
			/// </summary>
			public readonly static Field dId = new Field("dId","zkpt_mm_desktop","自增列，主键");
			/// <summary>
			/// 木马标识
			/// </summary>
			public readonly static Field tmark = new Field("tmark","zkpt_mm_desktop","木马标识");
			/// <summary>
			/// 添加时间
			/// </summary>
			public readonly static Field dAddTime = new Field("dAddTime","zkpt_mm_desktop","添加时间");
			/// <summary>
			/// 图片路径
			/// </summary>
			public readonly static Field dFilePath = new Field("dFilePath","zkpt_mm_desktop","图片路径");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field dRemark = new Field("dRemark","zkpt_mm_desktop","dRemark");
		}
		#endregion


	}
}

