//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Model
{

	/// <summary>
	/// 实体类zkpt_mm_Order 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("zkpt_mm_Order")]
	[Serializable]
	public partial class zkpt_mm_Order : Entity 
	{
		#region Model
		private int _Id;
		private string _StrOrder;
		private int? _IsHandle;
		private int? _Tid;
		private string _Tmark;
		private string _StrRandom;
		private string _SubOrder;
		private DateTime? _SetTime;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StrOrder
		{
			get{ return _StrOrder; }
			set
			{
				this.OnPropertyValueChange(_.StrOrder,_StrOrder,value);
				this._StrOrder=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? IsHandle
		{
			get{ return _IsHandle; }
			set
			{
				this.OnPropertyValueChange(_.IsHandle,_IsHandle,value);
				this._IsHandle=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Tid
		{
			get{ return _Tid; }
			set
			{
				this.OnPropertyValueChange(_.Tid,_Tid,value);
				this._Tid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Tmark
		{
			get{ return _Tmark; }
			set
			{
				this.OnPropertyValueChange(_.Tmark,_Tmark,value);
				this._Tmark=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StrRandom
		{
			get{ return _StrRandom; }
			set
			{
				this.OnPropertyValueChange(_.StrRandom,_StrRandom,value);
				this._StrRandom=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SubOrder
		{
			get{ return _SubOrder; }
			set
			{
				this.OnPropertyValueChange(_.SubOrder,_SubOrder,value);
				this._SubOrder=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? SetTime
		{
			get{ return _SetTime; }
			set
			{
				this.OnPropertyValueChange(_.SetTime,_SetTime,value);
				this._SetTime=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.StrOrder,
				_.IsHandle,
				_.Tid,
				_.Tmark,
				_.StrRandom,
				_.SubOrder,
				_.SetTime};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._StrOrder,
				this._IsHandle,
				this._Tid,
				this._Tmark,
				this._StrRandom,
				this._SubOrder,
				this._SetTime};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","zkpt_mm_Order");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","zkpt_mm_Order","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StrOrder = new Field("StrOrder","zkpt_mm_Order","StrOrder");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsHandle = new Field("IsHandle","zkpt_mm_Order","IsHandle");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Tid = new Field("Tid","zkpt_mm_Order","Tid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Tmark = new Field("Tmark","zkpt_mm_Order","Tmark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StrRandom = new Field("StrRandom","zkpt_mm_Order","StrRandom");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SubOrder = new Field("SubOrder","zkpt_mm_Order","SubOrder");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SetTime = new Field("SetTime","zkpt_mm_Order","SetTime");
		}
		#endregion


	}
}

